### ISSUE TITLE
Use library with Zephyr Scale 8.0.2-jira7

### ISSUE THREAD

**Issue by ssozinov** [devolo/pytest-adaptavist#19]
Hello ! Will this library work with Zephyr Scale 8.0.2-jira7?
Now i used : 
`@pytest.mark.project(project_key="PPP", test_run_suffix="11111")
class TestSCM(object):
    arm = None
    scm_dsr = None

    def test_T9299(self, meta_data):`

And I expect that a test run will be created and a test case with the key T9299 is attached to it. What am I doing wrong?

**Comment by 2Fake** [comment]
Hi,

we did a short test. The marker is working, except the test_run_suffix can not be set with this marker. But the suffix is just ignored, so this will not break anything. 

Did you start pytest with '--adaptavist' ?

**Comment by ssozinov** [comment]
Yes, I run with this argument
A test run is created, but test cases are not attached
How I can change name for Test-run?
How does linking a test case with a test run work?

**Comment by 2Fake** [comment]
Somehow we missed that we have set the project_key in our test environment this morning. It seems like that the marker ist NOT working as expected. We will provide a fix for that.

You can set that name for a test run in conftest.py like this:

```python
def pytest_sessionstart(session):
    pytest_adaptavist = session.config.pluginmanager.getplugin("_adaptavist")
    pytest_adaptavist.test_plan_suffix = "my test run name"
```

The linking of the test case with the testrun and reporting the results happens here

https://github.com/devolo/pytest-adaptavist/blob/main/pytest_adaptavist/_pytest_adaptavist.py#L174

**Comment by ssozinov** [comment]
thank you renaming the test runs works
now we are waiting for fix :)

**Comment by 2Fake** [comment]
You can use a global config to start. Then you don't have the need of a decorator at each class.

Just implement the steps you need as you would start the system tests

https://github.com/devolo/pytest-adaptavist/tree/main/tests#preconditions
