### ISSUE TITLE
Disable if jira_server is not set

### ISSUE THREAD

**Issue by jayvdb** [devolo/pytest-adaptavist#2]
I see errors lie `request failed. Invalid URL '/rest/api/2/user/search?username=.&startAt=0&maxResults=200': No schema supplied.` in the pytest startup, due to `jira_server` not being set.

The plugin should be inactive unless it has been given the required config values

**Comment by ststeinberg** [comment]
Hi @jayvdb, indeed the reporting to Jira resp. Adaptavist is disabled in this case.
The plugin itself is still active as there are features that work without Jira access (like selecting and reordering test cases).
