### ISSUE TITLE
Test cases are not attached to test run

### ISSUE THREAD

**Issue by nonameanon** [devolo/pytest-adaptavist#23]
Hello. We're having a trouble with test cases.
I've created Test object and added methods with *test_[test-case-key]* syntax, and after running, it only creates new test cycle, with no test cases attached to it. All keys are correct. Project key is also added to global_config file.
```python
@pytest.mark.project(project_key="TEST")
class TestIACM(object):
    def test_T8254(self, meta_data):
```

Is there any parameter in config that I might have missed? Or there is other way to add test cases to the cycle?

**Comment by 2Fake** [comment]
It looks correct on first view.

The test case TEST-T8254 exists in your test database?

**Comment by nonameanon** [comment]
Yes, it is. I've also tried with other cases, same result.
Also, Zephyr version is 8.0.2, if that is important.

**Comment by 2Fake** [comment]
Could you tell us your pytest and pytest-adptavist version?

**Comment by nonameanon** [comment]
pytest             6.2.5
pytest-adaptavist  5.1.2

**Comment by 2Fake** [comment]
Could you test with the following test case definition


def test_TEST_T8254(self, meta_data):

**Comment by nonameanon** [comment]
It worked! Thanks!

**Comment by 2Fake** [comment]
Great!

We will take a look if we have to change our Readme or the code.

Happy testing ;)

**Comment by 2Fake** [comment]
Merge request #24 should fix this issue
