### ISSUE TITLE
if jira unauthorised jira_username then test_run_key is inored and all tests collected to execute 

### ISSUE THREAD

**Issue by exmuzzy** [devolo/pytest-adaptavist#47]
https://github.com/devolo/pytest-adaptavist/blob/e833a303afacc9a13ba037929ebe5eb8231fcbab/pytest_adaptavist/_pytest_adaptavist.py#L863

**Comment by exmuzzy** [comment]
it's better not to run any test if jira reject requests

**Comment by Shutgun** [comment]
Hi @exmuzzy , thanks for reporting this issue. I fixed it in v5.8.0
